version: '3.3'
services:
  minio:
    container_name: minio
    image: "minio/minio:latest"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
      MINIO_USERNAME: "root"
      MINIO_GROUPNAME: "root"
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    command: "server /data"

  spark-master:
    container_name: spark-master
    image: "gemelen/spark:2.4.3-2.12-2.8.5"
    command: "/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./minio/data:/minio/data

  spark-worker:
    container_name: spark-worker
    image: "gemelen/spark:2.4.3-2.12-2.8.5"
    command: "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master:7077"
    ports:
      - "8081:8081"
    volumes:
      - ./minio/data:/minio/data
    depends_on:
      - spark-master

  top-songs:
    container_name: top-songs
    image: "top-songs:latest"
    environment:
      - MASTER=spark://spark-master:7077
    volumes:
      - ./minio/data:/minio/data
    depends_on:
      - minio
      - spark-worker
